name: Compliance Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas fairlearn

      - name: Run Bias Check
        run: python checks/bias_check.py

      - name: Run PII Check
        run: python checks/pii_check.py

      - name: Send Email if Failed
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚨 Compliance Check Failed in GitHub Actions"
          to: "danielchapman782@gmail.com"
          from: "danielchapman782@gmail.com"
          body: "One or more compliance checks failed. Please review the latest GitHub Actions run."
